/* 
  Author: Enio Carboni (enio.carboni@gmail.com)
  Download: https://github.com/eniocarboni/countrytocurrency
*/
class DefaultCurrency {
	constructor() {
		this.CountrytoCurrency = {
			    'AF' : {name: 'Afghanistan', currency_code: "AFN", currency_name: "Afghani"},
			    'AX' : {name: 'Aland Islands', currency_code: "EUR", currency_name: "Euro"},
			    'AL' : {name: 'Albania', currency_code: "ALL", currency_name: "Lek"},
			    'DZ' : {name: 'Algeria', currency_code: "DZD", currency_name: "Algerian Dinar"},
			    'AS' : {name: 'American Samoa', currency_code: "USD", currency_name: "US Dollar"},
			    'AD' : {name: 'Andorra', currency_code: "EUR", currency_name: "Euro"},
			    'AO' : {name: 'Angola', currency_code: "AOA", currency_name: "Kwanza"},
			    'AI' : {name: 'Anguilla', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'AG' : {name: 'Antigua And Barbuda', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'AR' : {name: 'Argentina', currency_code: "ARS", currency_name: "Argentine Peso"},
			    'AM' : {name: 'Armenia', currency_code: "AMD", currency_name: "Armenian Dram"},
			    'AW' : {name: 'Aruba', currency_code: "AWG", currency_name: "Aruban Florin"},
			    'AU' : {name: 'Australia', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'AT' : {name: 'Austria', currency_code: "EUR", currency_name: "Euro"},
			    'AZ' : {name: 'Azerbaijan', currency_code: "AZN", currency_name: "Azerbaijanian Manat"},
			    'BS' : {name: 'Bahamas', currency_code: "BSD", currency_name: "Bahamian Dollar"},
			    'BH' : {name: 'Bahrain', currency_code: "BHD", currency_name: "Bahraini Dinar"},
			    'BD' : {name: 'Bangladesh', currency_code: "BDT", currency_name: "Taka"},
			    'BB' : {name: 'Barbados', currency_code: "BBD", currency_name: "Barbados Dollar"},
			    'BY' : {name: 'Belarus', currency_code: "BYN", currency_name: "Belarusian Ruble"},
			    'BE' : {name: 'Belgium', currency_code: "EUR", currency_name: "Euro"},
			    'BZ' : {name: 'Belize', currency_code: "BZD", currency_name: "Belize Dollar"},
			    'BJ' : {name: 'Benin', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'BM' : {name: 'Bermuda', currency_code: "BMD", currency_name: "Bermudian Dollar"},
			    'BT' : {name: 'Bhutan', currency_code: "INR", currency_name: "Indian Rupee"},
			    'BO' : {name: 'Bolivia', currency_code: "BOV", currency_name: "Mvdol"},
			    'BA' : {name: 'Bosnia And Herzegovina', currency_code: "BAM", currency_name: "Convertible Mark"},
			    'BW' : {name: 'Botswana', currency_code: "BWP", currency_name: "Pula"},
			    'BV' : {name: 'Bouvet Island', currency_code: "NOK", currency_name: "Norwegian Krone"},
			    'BR' : {name: 'Brazil', currency_code: "BRL", currency_name: "Brazilian Real"},
			    'IO' : {name: 'British Indian Ocean Territory', currency_code: "USD", currency_name: "US Dollar"},
			    'BN' : {name: 'Brunei Darussalam', currency_code: "BND", currency_name: "Brunei Dollar"},
			    'BG' : {name: 'Bulgaria', currency_code: "BGN", currency_name: "Bulgarian Lev"},
			    'BF' : {name: 'Burkina Faso', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'BI' : {name: 'Burundi', currency_code: "BIF", currency_name: "Burundi Franc"},
			    'KH' : {name: 'Cambodia', currency_code: "KHR", currency_name: "Riel"},
			    'CM' : {name: 'Cameroon', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'CA' : {name: 'Canada', currency_code: "CAD", currency_name: "Canadian Dollar"},
			    'CV' : {name: 'Cabo Verde', currency_code: "CVE", currency_name: "Cabo Verde Escudo"},
			    'KY' : {name: 'Cayman Islands', currency_code: "KYD", currency_name: "Cayman Islands Dollar"},
			    'CF' : {name: 'Central African Republic', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'TD' : {name: 'Chad', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'CL' : {name: 'Chile', currency_code: "CLP", currency_name: "Chilean Peso"},
			    'CN' : {name: 'China', currency_code: "CNY", currency_name: "Yuan Renminbi"},
			    'CX' : {name: 'Christmas Island', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'CC' : {name: 'Cocos (Keeling) Islands', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'CO' : {name: 'Colombia', currency_code: "COP", currency_name: "Colombian Peso"},
			    'KM' : {name: 'Comoros', currency_code: "KMF", currency_name: "Comoro Franc"},
			    'CG' : {name: 'Congo, Democratic Republic of the', currency_code: "CDF", currency_name: "Congolese Franc"},
			    'CD' : {name: 'Congo', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'CK' : {name: 'Cook Islands', currency_code: "NZD", currency_name: "New Zealand Dollar"},
			    'CR' : {name: 'Costa Rica', currency_code: "CRC", currency_name: "Costa Rican Colon"},
			    'CI' : {name: 'Cote D\'Ivoire', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'HR' : {name: 'Croatia', currency_code: "HRK", currency_name: "Kuna"},
			    'CU' : {name: 'Cuba', currency_code: "CUP", currency_name: "Cuban Peso"},
			    'CY' : {name: 'Cyprus', currency_code: "EUR", currency_name: "Euro"},
			    'CZ' : {name: 'Czech Republic', currency_code: "CZK", currency_name: "Czech Koruna"},
			    'DK' : {name: 'Denmark', currency_code: "DKK", currency_name: "Danish Krone"},
			    'DJ' : {name: 'Djibouti', currency_code: "DJF", currency_name: "Djibouti Franc"},
			    'DM' : {name: 'Dominica', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'DO' : {name: 'Dominican Republic', currency_code: "DOP", currency_name: "Dominican Peso"},
			    'EC' : {name: 'Ecuador', currency_code: "USD", currency_name: "US Dollar"},
			    'EG' : {name: 'Egypt', currency_code: "EGP", currency_name: "Egyptian Pound"},
			    'SV' : {name: 'El Salvador', currency_code: "SVC", currency_name: "El Salvador Colon"},
			    'GQ' : {name: 'Equatorial Guinea', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'ER' : {name: 'Eritrea', currency_code: "ERN", currency_name: "Nakfa"},
			    'EE' : {name: 'Estonia', currency_code: "EUR", currency_name: "Euro"},
			    'ET' : {name: 'Ethiopia', currency_code: "ETB", currency_name: "Ethiopian Birr"},
			    'FK' : {name: 'Falkland Islands (Malvinas)', currency_code: "FKP", currency_name: "Falkland Islands Pound"},
			    'FO' : {name: 'Faroe Islands', currency_code: "DKK", currency_name: "Danish Krone"},
			    'FJ' : {name: 'Fiji', currency_code: "FJD", currency_name: "Fiji Dollar"},
			    'FI' : {name: 'Finland', currency_code: "EUR", currency_name: "Euro"},
			    'FR' : {name: 'France', currency_code: "EUR", currency_name: "Euro"},
			    'GF' : {name: 'French Guiana', currency_code: "EUR", currency_name: "Euro"},
			    'PF' : {name: 'French Polynesia', currency_code: "CFP", currency_name: "FRENCH POLYNESIA"},
			    'TF' : {name: 'French Southern Territories', currency_code: "EUR", currency_name: "Euro"},
			    'GA' : {name: 'Gabon', currency_code: "XAF", currency_name: "CFA Franc BEAC"},
			    'GM' : {name: 'Gambia', currency_code: "GMD", currency_name: "Dalasi"},
			    'GE' : {name: 'Georgia', currency_code: "GEL", currency_name: "Lari"},
			    'DE' : {name: 'Germany', currency_code: "EUR", currency_name: "Euro"},
			    'GH' : {name: 'Ghana', currency_code: "GHS", currency_name: "Ghana Cedi"},
			    'GI' : {name: 'Gibraltar', currency_code: "GIP", currency_name: "Gibraltar Pound"},
			    'GR' : {name: 'Greece', currency_code: "EUR", currency_name: "Euro"},
			    'GL' : {name: 'Greenland', currency_code: "DKK", currency_name: "Danish Krone"},
			    'GD' : {name: 'Grenada', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'GP' : {name: 'Guadeloupe', currency_code: "EUR", currency_name: "Euro"},
			    'GU' : {name: 'Guam', currency_code: "USD", currency_name: "US Dollar"},
			    'GT' : {name: 'Guatemala', currency_code: "GTQ", currency_name: "Quetzal"},
			    'GG' : {name: 'Guernsey', currency_code: "GBP", currency_name: "Pound Sterling"},
			    'GN' : {name: 'Guinea', currency_code: "GNF", currency_name: "Guinea Franc"},
			    'GW' : {name: 'Guinea-Bissau', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'GY' : {name: 'Guyana', currency_code: "GYD", currency_name: "Guyana Dollar"},
			    'HT' : {name: 'Haiti', currency_code: "HTG", currency_name: "Gourde"},
			    'HM' : {name: 'Heard Island & Mcdonald Islands', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'VA' : {name: 'Holy See (Vatican City State)', currency_code: "EUR", currency_name: "Euro"},
			    'HN' : {name: 'Honduras', currency_code: "HNL", currency_name: "Lempira"},
			    'HK' : {name: 'Hong Kong', currency_code: "HKD", currency_name: "Hong Kong Dollar"},
			    'HU' : {name: 'Hungary', currency_code: "HUF", currency_name: "Forint"},
			    'IS' : {name: 'Iceland', currency_code: "ISK", currency_name: "Iceland Krona"},
			    'IN' : {name: 'India', currency_code: "INR", currency_name: "Indian Rupee"},
			    'ID' : {name: 'Indonesia', currency_code: "IDR", currency_name: "Rupiah"},
			    'IR' : {name: 'Iran (Islamic Republic of)', currency_code: "IRR", currency_name: "Iranian Rial"},
			    'IQ' : {name: 'Iraq', currency_code: "IQD", currency_name: "Iraqi Dinar"},
			    'IE' : {name: 'Ireland', currency_code: "EUR", currency_name: "Euro"},
			    'IM' : {name: 'Isle Of Man', currency_code: "GBP", currency_name: "Pound Sterling"},
			    'IL' : {name: 'Israel', currency_code: "ILS", currency_name: "New Israeli Sheqel"},
			    'IT' : {name: 'Italy', currency_code: "EUR", currency_name: "Euro"},
			    'JM' : {name: 'Jamaica', currency_code: "JMD", currency_name: "Jamaican Dollar"},
			    'JP' : {name: 'Japan', currency_code: "JPY", currency_name: "Yen"},
			    'JE' : {name: 'Jersey', currency_code: "GBP", currency_name: "Pound Sterling"},
			    'JO' : {name: 'Jordan', currency_code: "JOD", currency_name: "Jordanian Dinar"},
			    'KZ' : {name: 'Kazakhstan', currency_code: "KZT", currency_name: "Tenge"},
			    'KE' : {name: 'Kenya', currency_code: "KES", currency_name: "Kenyan Shilling"},
			    'KI' : {name: 'Kiribati', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'KP' : {name: 'Korea (Democratic People\'s Republic of)', currency_code: "KPW", currency_name: "North Korean Won"},
			    'KR' : {name: 'Korea, Republic of', currency_code: "KRW", currency_name: "Won"},
			    'KW' : {name: 'Kuwait', currency_code: "KWD", currency_name: "Kuwaiti Dinar"},
			    'KG' : {name: 'Kyrgyzstan', currency_code: "KGS", currency_name: "Som"},
			    'LA' : {name: 'Lao People\'s Democratic Republic', currency_code: "LAK", currency_name: "Kip"},
			    'LV' : {name: 'Latvia', currency_code: "EUR", currency_name: "Euro"},
			    'LB' : {name: 'Lebanon', currency_code: "LBP", currency_name: "Lebanese Pound"},
			    'LS' : {name: 'Lesotho', currency_code: "LSL", currency_name: "Loti"},
			    'LR' : {name: 'Liberia', currency_code: "LRD", currency_name: "Liberian Dollar"},
			    'LY' : {name: 'Libya', currency_code: "LYD", currency_name: "Libyan Dinar"},
			    'LI' : {name: 'Liechtenstein', currency_code: "CHF", currency_name: "Swiss Franc"},
			    'LT' : {name: 'Lithuania', currency_code: "EUR", currency_name: "Euro"},
			    'LU' : {name: 'Luxembourg', currency_code: "EUR", currency_name: "Euro"},
			    'MO' : {name: 'Macao', currency_code: "MOP", currency_name: "Pataca"},
			    'MK' : {name: 'Macedonia', currency_code: "MKD", currency_name: "Denar"},
			    'MG' : {name: 'Madagascar', currency_code: "MGA", currency_name: "Malagasy Ariary"},
			    'MW' : {name: 'Malawi', currency_code: "MWK", currency_name: "Malawi Kwacha"},
			    'MY' : {name: 'Malaysia', currency_code: "MYR", currency_name: "Malaysian Ringgit"},
			    'MV' : {name: 'Maldives', currency_code: "MVR", currency_name: "Rufiyaa"},
			    'ML' : {name: 'Mali', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'MT' : {name: 'Malta', currency_code: "EUR", currency_name: "Euro"},
			    'MH' : {name: 'Marshall Islands', currency_code: "USD", currency_name: "US Dollar"},
			    'MQ' : {name: 'Martinique', currency_code: "EUR", currency_name: "Euro"},
			    'MR' : {name: 'Mauritania', currency_code: "MRO", currency_name: "Ouguiya"},
			    'MU' : {name: 'Mauritius', currency_code: "MUR", currency_name: "Mauritius Rupee"},
			    'YT' : {name: 'Mayotte', currency_code: "EUR", currency_name: "Euro"},
			    'MX' : {name: 'Mexico', currency_code: "MXN", currency_name: "Mexican Peso"},
			    'FM' : {name: 'Micronesia, currency_code, Federated States Of', currency_code: "USD", currency_name: "US Dollar"},
			    'MD' : {name: 'Moldova', currency_code: "MDL", currency_name: "Moldovan Leu"},
			    'MC' : {name: 'Monaco', currency_code: "EUR", currency_name: "Euro"},
			    'MN' : {name: 'Mongolia', currency_code: "MNT", currency_name: "Tugrik"},
			    'ME' : {name: 'Montenegro', currency_code: "EUR", currency_name: "Euro"},
			    'MS' : {name: 'Montserrat', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'MA' : {name: 'Morocco', currency_code: "MAD", currency_name: "Moroccan Dirham"},
			    'MZ' : {name: 'Mozambique', currency_code: "MZN", currency_name: "Mozambique Metical"},
			    'MM' : {name: 'Myanmar', currency_code: "MMK", currency_name: "Kyat"},
			    'NA' : {name: 'Namibia', currency_code: "NAD", currency_name: "Namibia Dollar"},
			    'NR' : {name: 'Nauru', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'NP' : {name: 'Nepal', currency_code: "NPR", currency_name: "Nepalese Rupee"},
			    'NL' : {name: 'Netherlands', currency_code: "EUR", currency_name: "Euro"},
			    'NC' : {name: 'New Caledonia', currency_code: "XPF", currency_name: "CFP Franc"},
			    'NZ' : {name: 'New Zealand', currency_code: "NZD", currency_name: "New Zealand Dollar"},
			    'NI' : {name: 'Nicaragua', currency_code: "NIO", currency_name: "Cordoba Oro"},
			    'NE' : {name: 'Niger', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'NG' : {name: 'Nigeria', currency_code: "NGN", currency_name: "Naira"},
			    'NU' : {name: 'Niue', currency_code: "NZD", currency_name: "New Zealand Dollar"},
			    'NF' : {name: 'Norfolk Island', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'MP' : {name: 'Northern Mariana Islands', currency_code: "USD", currency_name: "US Dollar"},
			    'NO' : {name: 'Norway', currency_code: "NOK", currency_name: "Norwegian Krone"},
			    'OM' : {name: 'Oman', currency_code: "OMR", currency_name: "Rial Omani"},
			    'PK' : {name: 'Pakistan', currency_code: "PKR", currency_name: "Pakistan Rupee"},
			    'PW' : {name: 'Palau', currency_code: "USD", currency_name: "US Dollar"},
			    'PS' : {name: 'Palestine, State of', currency_code: "", currency_name: ""},
			    'PA' : {name: 'Panama', currency_code: "PAB", currency_name: "Balboa"},
			    'PG' : {name: 'Papua New Guinea', currency_code: "PGK", currency_name: "Kina"},
			    'PY' : {name: 'Paraguay', currency_code: "PYG", currency_name: "Guarani"},
			    'PE' : {name: 'Peru', currency_code: "PEN", currency_name: "Sol"},
			    'PH' : {name: 'Philippines', currency_code: "PHP", currency_name: "Philippine Peso"},
			    'PN' : {name: 'Pitcairn', currency_code: "NZD", currency_name: "New Zealand Dollar"},
			    'PL' : {name: 'Poland', currency_code: "PLN", currency_name: "Zloty"},
			    'PT' : {name: 'Portugal', currency_code: "EUR", currency_name: "Euro"},
			    'PR' : {name: 'Puerto Rico', currency_code: "USD", currency_name: "US Dollar"},
			    'QA' : {name: 'Qatar', currency_code: "QAR", currency_name: "Qatari Rial"},
			    'RE' : {name: 'Reunion', currency_code: "EUR", currency_name: "Euro"},
			    'RO' : {name: 'Romania', currency_code: "RON", currency_name: "Romanian Leu"},
			    'RU' : {name: 'Russian Federation', currency_code: "RUB", currency_name: "Russian Ruble"},
			    'RW' : {name: 'Rwanda', currency_code: "RWF", currency_name: "Rwanda Franc"},
			    'BL' : {name: 'Saint Barthelemy', currency_code: "EUR", currency_name: "Euro"},
			    'SH' : {name: 'Saint Helena, Ascension and Tristan da Cunha', currency_code: "SHP", currency_name: "Saint Helena Pound"},
			    'KN' : {name: 'Saint Kitts And Nevis', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'LC' : {name: 'Saint Lucia', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'MF' : {name: 'Saint Martin', currency_code: "EUR", currency_name: "Euro"},
			    'PM' : {name: 'Saint Pierre And Miquelon', currency_code: "EUR", currency_name: "Euro"},
			    'VC' : {name: 'Saint Vincent And Grenadines', currency_code: "XCD", currency_name: "East Caribbean Dollar"},
			    'WS' : {name: 'Samoa', currency_code: "WST", currency_name: "Tala"},
			    'SM' : {name: 'San Marino', currency_code: "EUR", currency_name: "Euro"},
			    'ST' : {name: 'Sao Tome And Principe', currency_code: "STD", currency_name: "Dobra"},
			    'SA' : {name: 'Saudi Arabia', currency_code: "SAR", currency_name: "Saudi Riyal"},
			    'SN' : {name: 'Senegal', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'RS' : {name: 'Serbia', currency_code: "RSD", currency_name: "Serbian Dinar"},
			    'SC' : {name: 'Seychelles', currency_code: "SCR", currency_name: "Seychelles Rupee"},
			    'SL' : {name: 'Sierra Leone', currency_code: "SLL", currency_name: "Leone"},
			    'SG' : {name: 'Singapore', currency_code: "SGD", currency_name: "Singapore Dollar"},
			    'SK' : {name: 'Slovakia', currency_code: "EUR", currency_name: "Euro"},
			    'SI' : {name: 'Slovenia', currency_code: "EUR", currency_name: "EUR"},
			    'SB' : {name: 'Solomon Islands', currency_code: "SBD", currency_name: "Solomon Islands Dollar"},
			    'SO' : {name: 'Somalia', currency_code: "SOS", currency_name: "Somali Shilling"},
			    'ZA' : {name: 'South Africa', currency_code: "ZAR", currency_name: "Rand"},
			    'GS' : {name: 'South Georgia And Sandwich Isl.', currency_code: "", currency_name: ""},
			    'SS' : {name: 'South Sudan', currency_code: "SSP", currency_name: "South Sudanese Pound"},
			    'ES' : {name: 'Spain', currency_code: "EUR", currency_name: "Euro"},
			    'LK' : {name: 'Sri Lanka', currency_code: "LKR", currency_name: "Sri Lanka Rupee"},
			    'SD' : {name: 'Sudan', currency_code: "SDG", currency_name: "Sudanese Pound"},
			    'SR' : {name: 'Suriname', currency_code: "SRD", currency_name: "Surinam Dollar"},
			    'SJ' : {name: 'Svalbard And Jan Mayen', currency_code: "NOK", currency_name: "Norwegian Krone"},
			    'SZ' : {name: 'Swaziland', currency_code: "SZL", currency_name: "Lilangeni"},
			    'SE' : {name: 'Sweden', currency_code: "SEK", currency_name: "Swedish Krona"},
			    'CH' : {name: 'Switzerland', currency_code: "CHF", currency_name: "Swiss Franc"},
			    'SY' : {name: 'Syrian Arab Republic', currency_code: "SYP", currency_name: "Syrian Pound"},
			    'TW' : {name: 'Taiwan', currency_code: "TWD", currency_name: "New Taiwan Dollar"},
			    'TJ' : {name: 'Tajikistan', currency_code: "TJS", currency_name: "Somoni"},
			    'TZ' : {name: 'Tanzania', currency_code: "TZS", currency_name: "Tanzanian Shilling"},
			    'TH' : {name: 'Thailand', currency_code: "THB", currency_name: "Baht"},
			    'TL' : {name: 'Timor-Leste', currency_code: "USD", currency_name: "US Dollar"},
			    'TG' : {name: 'Togo', currency_code: "XOF", currency_name: "CFA Franc BCEAO"},
			    'TK' : {name: 'Tokelau', currency_code: "NZD", currency_name: "New Zealand Dollar"},
			    'TO' : {name: 'Tonga', currency_code: "TOP", currency_name: "Pa\u2019anga"},
			    'TT' : {name: 'Trinidad And Tobago', currency_code: "TTD", currency_name: "Trinidad and Tobago Dollar"},
			    'TN' : {name: 'Tunisia', currency_code: "TND", currency_name: "Tunisian Dinar"},
			    'TR' : {name: 'Turkey', currency_code: "TRY", currency_name: "Turkish Lira"},
			    'TM' : {name: 'Turkmenistan', currency_code: "TMT", currency_name: "Turkmenistan New Manat"},
			    'TC' : {name: 'Turks And Caicos Islands', currency_code: "USD", currency_name: "US Dollar"},
			    'TV' : {name: 'Tuvalu', currency_code: "AUD", currency_name: "Australian Dollar"},
			    'UG' : {name: 'Uganda', currency_code: "UGX", currency_name: "Uganda Shilling"},
			    'UA' : {name: 'Ukraine', currency_code: "UAH", currency_name: "Hryvnia"},
			    'AE' : {name: 'United Arab Emirates', currency_code: "AED", currency_name: "UAE Dirham"},
			    'GB' : {name: 'United Kingdom', currency_code: "GBP", currency_name: "Pound Sterling"},
			    'US' : {name: 'United States', currency_code: "USD", currency_name: "US Dollar"},
			    'UM' : {name: 'United States Outlying Islands', currency_code: "USD", currency_name: "US Dollar"},
			    'UY' : {name: 'Uruguay', currency_code: "UYU", currency_name: "Peso Uruguayo"},
			    'UZ' : {name: 'Uzbekistan', currency_code: "UZS", currency_name: "Uzbekistan Sum"},
			    'VU' : {name: 'Vanuatu', currency_code: "VUV", currency_name: "Vatu"},
			    'VE' : {name: 'Venezuela', currency_code: "VEF", currency_name: "Bol\u00edvar"},
			    'VN' : {name: 'Viet Nam', currency_code: "VND", currency_name: "Dong"},
			    'VG' : {name: 'Virgin Islands, currency_code, British', currency_code: "USD", currency_name: "US Dollar"},
			    'VI' : {name: 'Virgin Islands, currency_code, U.S.', currency_code: "USD", currency_name: "US Dollar"},
			    'WF' : {name: 'Wallis And Futuna', currency_code: "XPF", currency_name: "Moroccan Dirham"},
			    'EH' : {name: 'Western Sahara', currency_code: "MAD", currency_name: "Moroccan Dirham"},
			    'YE' : {name: 'Yemen', currency_code: "YER", currency_name: "Yemeni Rial"},
			    'ZM' : {name: 'Zambia', currency_code: "ZMW", currency_name: "Zambian Kwacha"},
			    'ZW' : {name: 'Zimbabwe', currency_code: "ZWL", currency_name: "Zimbabwe Dollar"}
		};
		this.dcc=this.getDefaultCoutryCode();
		this.dcn=this.getCountryName(this.dcc);
		this.cc=this.getCurrencyCode(this.dcc);
		this.cn=this.getCurrencyName(this.dcc);
	}
	
	getDefaultCoutryCode() {
	  var l=navigator.language || 'EN-US';
	  var l_c=l.split("-");
	  var dcc=l_c[1] || l_c[0];
	  dcc=dcc.substring(0, 2).toUpperCase();
	  return dcc;
	}
	
	getCountryName(countryCode) {
	    if (this.CountrytoCurrency.hasOwnProperty(countryCode)) {
	        return this.CountrytoCurrency[countryCode].name;
	    } else {
	        return 'US';
	    }
	}
	getCurrencyCode(countryCode) {
	    if (this.CountrytoCurrency.hasOwnProperty(countryCode)) {
	        return this.CountrytoCurrency[countryCode].currency_code;
	    } else {
	        return this.CountrytoCurrency['US'].currency_code;
	    }
	}
	getCurrencyName(countryCode) {
	    if (this.CountrytoCurrency.hasOwnProperty(countryCode)) {
	        return this.CountrytoCurrency[countryCode].currency_name;
	    } else {
	        return this.CountrytoCurrency['US'].currency_name;
	    }
	}
	getAllCurrency() {
		var curr={};
		for ( var cc in this.CountrytoCurrency) {
		  if (! this.CountrytoCurrency[cc].currency_code) { continue; }
		  curr[this.CountrytoCurrency[cc].currency_code]=this.CountrytoCurrency[cc].currency_name;
		}
		return curr;
	}
};
